export const START_RECORDING = 'START_RECORDING';
export const ON_VOICE_RECORDED = 'ON_VOICE_RECORDED';
export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const SEARCH_DONE = 'SEARCH_DONE';