export const SEARCH_IN_PROGRESS = 'SEARCH_IN_PROGRESS';
export const SEARCH_DONE = 'SEARCH_DONE';

export const SPEECH_RECOGNITION_DETECTED = 'SPEECH_RECOGNITION_DETECTED';
export const START_RECORDING = 'START_RECORDING';
export const VOICE_RECORDED = 'VOICE_RECORDED';
